name: CommitEmpty4Deploy

on:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Validate Actor
      run: test $GITHUB_ACTOR = "515hikaru" || exit 1
    - uses: actions/checkout@v2
    - name: Git Config
      run: |
        git config --local user.email "12kojima.takahiro@gmail.com"
        git config --local user.name "515hikaru"
    - name: Commit
      run: git commit --allow-empty -m "commit for deploy"
    - name: Push
      run: git push origin main
